spring:
  application:
    name: ride-service

  datasource:
    url: ${RIDE_DB_URL:jdbc:postgresql://localhost:5432/pulseride_rides}
    username: ${RIDE_DB_USERNAME:postgres}
    password: ${RIDE_DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${RIDE_JPA_DDL_AUTO:update}
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${RIDE_SERVICE_PORT:8084}
  servlet:
    context-path: /pulse-ride

jwt:
  secret: ${JWT_SECRET:ca3ae9dc7984009cfa286be0ffeabd5e78b0620e51fbf7f1f40c1811ca08b781}
  issuer: ${JWT_ISSUER:pulseride-auth}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}