package com.pulseride.payment.service;
import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*; import java.util.concurrent.ConcurrentHashMap; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import com.pulseride.payment.gateway.PaymentGateway; import jakarta.validation.constraints.*;
@Service public class PaymentService {
 public enum State { CREATED,PENDING,SUCCESS,FAILED,REFUNDED,PARTIALLY_REFUNDED }
 public record OrderRequest(@NotNull @Positive BigDecimal amount,@NotBlank String currency){}
 public record PaymentResponse(String id,String owner,BigDecimal amount,String currency,State state){}
 private final Map<String,Record> payments=new ConcurrentHashMap<>(); private final Map<String,String> keys=new ConcurrentHashMap<>(); private final String webhookSecret; private final PaymentGateway gateway;
 public PaymentService(@Value("${payment.webhook-secret}") String secret, PaymentGateway gateway){webhookSecret=secret;this.gateway=gateway;}
 public PaymentResponse order(String owner,String key,OrderRequest req){String existing=keys.get("order:"+owner+":"+key);if(existing!=null)return response(payments.get(existing));String id=UUID.randomUUID().toString();Record p=new Record(id,owner,req.amount(),req.currency());payments.put(id,p);keys.put("order:"+owner+":"+key,id);gateway.createOrder(req.amount(),req.currency(),id);return response(p);}
 public PaymentResponse get(String owner,String id){Record p=owned(owner,id);return response(p);}
 public PaymentResponse verify(String owner,String id,String key){String marker="verify:"+owner+":"+id+":"+key;if(keys.putIfAbsent(marker,id)!=null)return response(owned(owner,id));Record p=owned(owner,id);if(p.state==State.CREATED||p.state==State.PENDING)p.state=State.SUCCESS;return response(p);}
 public PaymentResponse refund(String owner,String id,String key){String marker="refund:"+owner+":"+id+":"+key;if(keys.putIfAbsent(marker,id)!=null)return response(owned(owner,id));Record p=owned(owner,id);if(p.state!=State.SUCCESS)throw new IllegalStateException("Payment is not refundable");p.state=State.REFUNDED;return response(p);}
 public void webhook(String provider,String signature,String payload){try{var mac=javax.crypto.Mac.getInstance("HmacSHA256");mac.init(new javax.crypto.spec.SecretKeySpec(webhookSecret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));String expected=Base64.getEncoder().encodeToString(mac.doFinal(payload.getBytes(StandardCharsets.UTF_8)));if(!MessageDigest.isEqual(expected.getBytes(StandardCharsets.UTF_8),signature.getBytes(StandardCharsets.UTF_8)))throw new SecurityException("Invalid webhook signature");}catch(Exception e){throw new SecurityException("Invalid webhook signature",e);}}
 private Record owned(String owner,String id){Record p=payments.get(id);if(p==null)throw new IllegalArgumentException("Payment not found");if(!p.owner.equals(owner))throw new AccessDeniedException("Payment does not belong to authenticated user");return p;} private PaymentResponse response(Record p){return new PaymentResponse(p.id,p.owner,p.amount,p.currency,p.state);} private static final class Record{final String id,owner;final BigDecimal amount;final String currency;State state=State.CREATED;Record(String i,String o,BigDecimal a,String c){id=i;owner=o;amount=a;currency=c;}}
}
